server:
  port: 8002
spring:
  rabbitmq:
    addresses: 192.168.0.122:5672,192.168.0.123:5672,192.168.0.124:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true   # 是否启用消息确认的模式
    listener:
      simple:
        acknowledge-mode: manual    # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认为auto
        concurrency: 5
        prefetch: 1
        max-concurrency: 10
    # 设置return消息模式，注意要和mandatory一起去配合使用
#    publisher-returns: true
#    template:
#      mandatory: true