server:
  port: 8001
spring:
  rabbitmq:
    addresses: 192.168.0.122:5672,192.168.0.123:5672,192.168.0.124:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true   # 是否启用消息确认的模式
    # 设置return消息模式，注意要和mandatory一起去配合使用
#    publisher-returns: true
#    template:
#      mandatory: true