server:
  port: 8049
spring:
  elasticsearch:
    rest:
      uris: 192.168.52.131:9200
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    # Redis单机单实例
    database: 0
    host: 192.168.52.201
    port: 6379
    password: 123456
